name: Deploy testflight
on:
  workflow_dispatch:
    inputs:
      variant:
        description: The variant to deploy to
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - production
      platform:
        description: The platform to deploy to
        required: true
        default: 'ios'
        type: choice
        options:
          - ios
          - android
env:
  TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID_STAGING }}
  TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET_STAGING }}
  AUTH_PROXY_API_BASE_URL: ${{ secrets.AUTH_PROXY_API_BASE_URL_STAGING }} 
  AUTH_PROXY_API_KEY: ${{ secrets.AUTH_PROXY_API_KEY_STAGING }}
jobs:
  deploy:
    runs-on: macos-latest
    if: github.actor == 'luke-h1'
    concurrency: deploy-testflight-${{ github.run_id }}
    steps:
      - name: ðŸ”Ž Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/tutorial/eas/using-github/"
            exit 1
          fi

      - name: ðŸ— Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: ðŸ¥Ÿ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: Setup Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .nvmrc

      - name: ðŸ“¦ Install dependencies
        run: bun install --frozen-lockfile

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: â˜•ï¸ Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest  

      - name: Write .env file
        run: |
          echo "TWITCH_CLIENT_ID=${{ env.TWITCH_CLIENT_ID }}" >> .env
          echo "TWITCH_CLIENT_SECRET=${{ env.TWITCH_CLIENT_SECRET }}" >> .env
          echo "AUTH_PROXY_API_BASE_URL=${{ env.AUTH_PROXY_API_BASE_URL }}" >> .env
          echo "AUTH_PROXY_API_KEY=${{ env.AUTH_PROXY_API_KEY }}" >> .env

      - name: Î› Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun


      - name: EAS build
        run: |
          if [ "${{ inputs.platform }}" = "ios" ]; then
            bun eas build -p ios --profile ${{ inputs.variant }} --local --output app-${{ inputs.variant }}.abd --non-interactive
            # bun eas submit -p ios --path ./app-${{ inputs.variant }}.abd

          else
            bun eas build -p android --profile ${{ inputs.variant }} --local --output app-${{ inputs.variant }}.apk --non-interactive
            # bun eas submit -p android --path ./app-${{ inputs.variant }}.apk
          fi

      - name: Deploy ðŸš€
        run: |
          if [ "${{ inputs.platform }}" = "ios" ]; then
            bun eas submit -p ios --path ./app-${{ inputs.variant }}.abd
          else
            bun eas submit -p android --path ./app-${{ inputs.variant }}.apk
          fi